loadbalancer:
  image: nginx
  container_name: loadbalancer
  ports:
   - 80:80
   - 443:443
  environment:
    - NGINX_HOST=dev.portaltecsinapse.com.br
  volumes:
   - /Users/anselmo/Documents/Desenvolvimento/workspace/DevOps/learning-docker/HighAvailability/exemplo04-compose/cluster/error.html:/usr/share/nginx/html/error.html
   - /Users/anselmo/Documents/Desenvolvimento/workspace/DevOps/learning-docker/HighAvailability/exemplo04-compose/cluster/default.conf:/etc/nginx/conf.d/default.conf
  links:
   - tomcatOne:tomcat1
   - tomcatTwo:tomcat2
   - tomcatThree:tomcat3

tomcatOne:
  image: tomcat
  container_name: tomcat1
  ports:
    - 8081:8080
  volumes:
    - /Users/anselmo/Documents/Desenvolvimento/workspace/DevOps/learning-docker/HighAvailability/exemplo04-compose/cluster/server.xml:/usr/local/tomcat/conf/server.xml
    - /Users/anselmo/Documents/Desenvolvimento/workspace/DevOps/learning-docker/HighAvailability/exemplo04-compose/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - /Users/anselmo/Documents/Desenvolvimento/workspace/DevOps/learning-docker/HighAvailability/exemplo04-compose/cluster/ROOT:/usr/local/tomcat/webapps/ROOT

tomcatTwo:
  image: tomcat
  container_name: tomcat2
  ports:
    - 8082:8080
  volumes:
    - /Users/anselmo/Documents/Desenvolvimento/workspace/DevOps/learning-docker/HighAvailability/exemplo04-compose/cluster/server.xml:/usr/local/tomcat/conf/server.xml
    - /Users/anselmo/Documents/Desenvolvimento/workspace/DevOps/learning-docker/HighAvailability/exemplo04-compose/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - /Users/anselmo/Documents/Desenvolvimento/workspace/DevOps/learning-docker/HighAvailability/exemplo04-compose/cluster/ROOT:/usr/local/tomcat/webapps/ROOT

tomcatThree:
  image: tomcat
  container_name: tomcat3
  ports:
    - 8083:8080
  volumes:
    - /Users/anselmo/Documents/Desenvolvimento/workspace/DevOps/learning-docker/HighAvailability/exemplo04-compose/cluster/server.xml:/usr/local/tomcat/conf/server.xml
    - /Users/anselmo/Documents/Desenvolvimento/workspace/DevOps/learning-docker/HighAvailability/exemplo04-compose/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - /Users/anselmo/Documents/Desenvolvimento/workspace/DevOps/learning-docker/HighAvailability/exemplo04-compose/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
